# Generated by Django 4.2.6 on 2023-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='visible',
            field=models.BooleanField(default=1),
        ),
    ]
