# Generated by Django 4.2.6 on 2023-10-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_comunicado_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidades',
            options={'verbose_name_plural': 'Entidades'},
        ),
    ]
